version: "3.3"
services:

  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --experimental.localPlugins.torblock.moduleName=github.com/jpxd/torblock
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../.:/plugins-local/src/github.com/jpxd/torblock

  whoami:
    image: traefik/whoami:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`localhost`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.middlewares.block-tor-middleware.plugin.torblock.enabled=true
      - traefik.http.routers.whoami.middlewares=block-tor-middleware@docker
